import type { SnapshotItem } from "./types.js";

export const SNAPSHOT_ITEMS: SnapshotItem[] = [
  {
    "id": "manual-mona-lisa",
    "title": "Mona Lisa",
    "creator": "Leonardo da Vinci",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Mona%20Lisa%2C%20by%20Leonardo%20da%20Vinci%2C%20from%20C2RMF%20retouched.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
    "lat": 48.86,
    "lon": 2.337,
    "placeName": "Paris",
    "year": 1506,
    "license": "Public Domain"
  },
  {
    "id": "manual-starry-night",
    "title": "The Starry Night",
    "creator": "Vincent van Gogh",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/The%20Starry%20Night.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:The_Starry_Night.jpg",
    "lat": 43.723,
    "lon": 5.775,
    "placeName": "Saint-Rémy-de-Provence",
    "year": 1889,
    "license": "Public Domain"
  },
  {
    "id": "manual-great-wave",
    "title": "The Great Wave off Kanagawa",
    "creator": "Katsushika Hokusai",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/The%20Great%20Wave%20off%20Kanagawa.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:The_Great_Wave_off_Kanagawa.jpg",
    "lat": 35.1,
    "lon": 139.05,
    "placeName": "Kanagawa",
    "year": 1831,
    "license": "Public Domain"
  },
  {
    "id": "manual-guernica",
    "title": "Guernica",
    "creator": "Pablo Picasso",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Guernica%20(decorative)%20-%20Madrid%2C%20Spain.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Guernica_(decorative)_-_Madrid,_Spain.jpg",
    "lat": 43.311,
    "lon": -2.678,
    "placeName": "Guernica",
    "year": 1937,
    "license": "CC BY-SA 4.0 (photo of mural after Picasso)"
  },
  {
    "id": "manual-last-supper",
    "title": "The Last Supper",
    "creator": "Leonardo da Vinci",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo_da_Vinci_(1452-1519)_-_The_Last_Supper_(1495-1498).jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Leonardo_da_Vinci_(1452-1519)_-_The_Last_Supper_(1495-1498).jpg",
    "lat": 45.465,
    "lon": 9.17,
    "placeName": "Milan",
    "year": 1498,
    "license": "Public Domain"
  },
  {
    "id": "manual-pearl-earring",
    "title": "Girl with a Pearl Earring",
    "creator": "Johannes Vermeer",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/1665%20Girl%20with%20a%20Pearl%20Earring.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:1665_Girl_with_a_Pearl_Earring.jpg",
    "lat": 52.08,
    "lon": 4.314,
    "placeName": "The Hague",
    "year": 1665,
    "license": "Public Domain"
  },
  {
    "id": "manual-scream",
    "title": "The Scream",
    "creator": "Edvard Munch",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/The%20Scream.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:The_Scream.jpg",
    "lat": 59.91,
    "lon": 10.749,
    "placeName": "Oslo",
    "year": 1893,
    "license": "Public Domain"
  },
  {
    "id": "manual-night-watch",
    "title": "The Night Watch",
    "creator": "Rembrandt",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/The%20Night%20Watch%20-%20HD.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:The_Night_Watch_-_HD.jpg",
    "lat": 52.375,
    "lon": 4.884,
    "placeName": "Amsterdam",
    "year": 1642,
    "license": "Public Domain"
  },
  {
    "id": "manual-sunday-grande-jatte",
    "title": "A Sunday on La Grande Jatte",
    "creator": "Georges Seurat",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Georges_Seurat%2C%201884-1886%2C%20Un%20dimanche%20%C3%A0%20la%20Grande%20Jatte%2C%201884-1886.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Georges_Seurat,_1884-1886,_Un_dimanche_%C3%A0_la_Grande_Jatte,_1884-1886.jpg",
    "lat": 48.896,
    "lon": 2.263,
    "placeName": "Paris",
    "year": 1886,
    "license": "Public Domain"
  },
  {
    "id": "manual-water-lilies",
    "title": "Water Lilies",
    "creator": "Claude Monet",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Claude_Monet%2C_Impression%2C_soleil_levant%2C_1872.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Claude_Monet,_Impression,_soleil_levant,_1872.jpg",
    "lat": 49.493,
    "lon": 0.108,
    "placeName": "Le Havre",
    "year": 1872,
    "license": "Public Domain"
  },
  {
    "id": "manual-liberty-leading",
    "title": "Liberty Leading the People",
    "creator": "Eugène Delacroix",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg",
    "lat": 48.856,
    "lon": 2.352,
    "placeName": "Paris",
    "year": 1830,
    "license": "Public Domain"
  },
  {
    "id": "manual-birth-venus",
    "title": "The Birth of Venus",
    "creator": "Sandro Botticelli",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    "lat": 43.723,
    "lon": 10.396,
    "placeName": "Florence",
    "year": 1485,
    "license": "Public Domain"
  },
  {
    "id": "manual-arnolfini",
    "title": "Arnolfini Portrait",
    "creator": "Jan van Eyck",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/The_Arnolfini_portrait_(1434).jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:The_Arnolfini_portrait_(1434).jpg",
    "lat": 51.209,
    "lon": 3.224,
    "placeName": "Bruges",
    "year": 1434,
    "license": "Public Domain"
  },
  {
    "id": "manual-kiss-klimt",
    "title": "The Kiss",
    "creator": "Gustav Klimt",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
    "lat": 48.208,
    "lon": 16.373,
    "placeName": "Vienna",
    "year": 1908,
    "license": "Public Domain"
  },
  {
    "id": "manual-sistine",
    "title": "The Creation of Adam (Sistine Chapel)",
    "creator": "Michelangelo",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Creaci%C3%B3n_de_Ad%C3%A1n.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Creaci%C3%B3n_de_Ad%C3%A1n.jpg",
    "lat": 41.903,
    "lon": 12.454,
    "placeName": "Vatican City",
    "year": 1512,
    "license": "Public Domain"
  },
  {
    "id": "manual-eiffel-1889",
    "title": "Eiffel Tower under construction",
    "creator": "Unknown photographer",
    "kind": "photo",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Tour_Eiffel%2C_1888.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Tour_Eiffel,_1888.jpg",
    "lat": 48.858,
    "lon": 2.294,
    "placeName": "Paris",
    "year": 1888,
    "license": "Public Domain"
  },
  {
    "id": "manual-brooklyn-bridge-1900",
    "title": "Brooklyn Bridge",
    "creator": "Unknown photographer",
    "kind": "photo",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Brooklyn_Bridge%2C_New_York%2C_ca._1900.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Brooklyn_Bridge,_New_York,_ca._1900.jpg",
    "lat": 40.706,
    "lon": -73.997,
    "placeName": "New York",
    "year": 1900,
    "license": "Public Domain"
  },
  {
    "id": "manual-sphinx-1860",
    "title": "Great Sphinx of Giza",
    "creator": "Francis Frith",
    "kind": "photo",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/The_Great_Sphinx%2C_Pyramids_of_Gizeh%2C_1858.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:The_Great_Sphinx,_Pyramids_of_Gizeh,_1858.jpg",
    "lat": 29.975,
    "lon": 31.138,
    "placeName": "Giza",
    "year": 1858,
    "license": "Public Domain"
  },
  {
    "id": "manual-taj-1860",
    "title": "Taj Mahal",
    "creator": "Samuel Bourne",
    "kind": "photo",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Taj_Mahal%2C_Agra%2C_India%2C_1860s.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Taj_Mahal,_Agra,_India,_1860s.jpg",
    "lat": 27.175,
    "lon": 78.042,
    "placeName": "Agra",
    "year": 1865,
    "license": "Public Domain"
  },
  {
    "id": "manual-colosseum-1870",
    "title": "Colosseum, Rome",
    "creator": "Unknown photographer",
    "kind": "photo",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Colosseum%2C_Rome%2C_Italy%2C_ca._1870.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Colosseum,_Rome,_Italy,_ca._1870.jpg",
    "lat": 41.89,
    "lon": 12.492,
    "placeName": "Rome",
    "year": 1870,
    "license": "Public Domain"
  },
  {
    "id": "manual-niagara-1860",
    "title": "Niagara Falls",
    "creator": "Unknown photographer",
    "kind": "photo",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Niagara_Falls%2C_ca._1860.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Niagara_Falls,_ca._1860.jpg",
    "lat": 43.096,
    "lon": -79.037,
    "placeName": "Niagara Falls",
    "year": 1860,
    "license": "Public Domain"
  },
  {
    "id": "manual-kyoto-1870",
    "title": "Kiyomizu-dera, Kyoto",
    "creator": "Unknown photographer",
    "kind": "photo",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Kiyomizu-dera%2C_Kyoto%2C_ca._1870.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Kiyomizu-dera,_Kyoto,_ca._1870.jpg",
    "lat": 34.995,
    "lon": 135.785,
    "placeName": "Kyoto",
    "year": 1870,
    "license": "Public Domain"
  },
  {
    "id": "manual-sydney-harbour-1900",
    "title": "Sydney Harbour Bridge construction",
    "creator": "Unknown photographer",
    "kind": "photo",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Sydney_Harbour%2C_ca._1900.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Sydney_Harbour,_ca._1900.jpg",
    "lat": -33.852,
    "lon": 151.21,
    "placeName": "Sydney",
    "year": 1900,
    "license": "Public Domain"
  },
  {
    "id": "manual-venice-canaletto",
    "title": "The Grand Canal, Venice",
    "creator": "Canaletto",
    "kind": "painting",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Canaletto%2C_Il_Canal_Grande_verso_est.jpg?width=800",
    "page": "https://commons.wikimedia.org/wiki/File:Canaletto,_Il_Canal_Grande_verso_est.jpg",
    "lat": 45.44,
    "lon": 12.335,
    "placeName": "Venice",
    "year": 1730,
    "license": "Public Domain"
  }
];
